# Generated by Django 5.2.4 on 2025-07-12 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_index=True, max_length=100)),
                ('audio_file', models.FileField(upload_to='audio/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('language', models.CharField(default='en', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_caches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'word', 'language')},
            },
        ),
    ]
